workflows:
  ios-release:
    name: iOS Release Workflow
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      vars:
        APP_ID: "com.westministertechnology.orderanddelivery"
        SHOREBIRD_TOKEN: $SHOREBIRD_TOKEN # optional if using Shorebird
      groups:
        - app_store_credentials
    scripts:
      - name: Clean previous builds
        script: |
          flutter clean
          rm -rf ios/Pods ios/Podfile.lock
      - name: Install Flutter dependencies
        script: flutter pub get
      - name: Update CocoaPods repo
        script: pod repo update
      - name: Install CocoaPods
        script: |
          cd ios
          pod install
          cd ..
      - name: Build iOS .ipa
        script: |
          flutter build ipa --release --export-options-plist=ExportOptions.plist
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        apple_id: Sabdulle@westminister.tech
        api_key: X7P22DJ3UC
        issuer_id: 641018e4-2e33-434e-8aa4-2ae11d0e553d
        submit_to_testflight: true
